

## 接口在访问时报500，控制台报错：com.netflix.client.ClientException: Load balancer does not have available server for client: uniqc
原因：可能是因为其他微服务的断点还没继续走完，卡在那里，导致该微服务目前不能被其他请求使用


## feign.FeignException$InternalServerError: [500] during [POST] to [http://uniqc/rpc/hospital/department/followup-bodypart/972115597723172864/side] [FollowupBodypartConfigRpc#addBodypartSide(String,SaveFollowupBodypartSideCommandDto)]: [{"data":null,"success":false,"status":1004,"message":"Internal Server Error","errorData":null}]
原因：应该是其他的微服务中出现问题，被远程调用的方法或是使用远程调用方法的方法存在异常,方法中的异常比如除零异常等,都会通过 feign.FeignException: status 500 reading… 的方式基于你提示。   
详细排查了之后，是代码中有空指针异常，导致远程调用返回这个错误。


## 报 Controller 参数解析错误
原因1：在 `QcGroupAddExpertCommandDto` 类中字段 `qcGroupId` 写成了 `qcGorupId`。  
原因2：在 `QcGroupRpcService` 接口中 `addGroupRelExpert` 方法和 `deleteQcGroupRelExpert` 方法被加上了 `@Validated`、`@RequestBody` 注解，这两个注解应该是在 Controller 接口中的，这里不需要加。  
原因3：`QcGroupRelExpertListCommand` 中字段原本加的是 `NotBlank` 注解，理论上来说这里应该没问题，但事实证明确实是这里导致的报错，将其改为跟前端接口统一的注解 `NotEmpty`。  



# 单元测试

## 测试类中测试方法旁边没有运行箭头
解决方法：  
1. 注意类的修饰符要为public
2. 方法修饰符不可含有static
3. 测试方法无返回值

## 运行测试类中方法的时候报空指针异常，bean 没注入进去。
可能原因一：Junit 不匹配
Junit4在类的开头使用的是@RunWith，Junit5中类的前面使用的@ExtendWith    
Junit4的“@Test”需要导入的是org.junit.Test，而Junit5的“@Test”这个注解，需要导入的是org.junit.jupiter.api.Test


## 报错 Method threw 'org.mockito.exceptions.misusing.InvalidUseOfMatchersException' exception. Cannot evaluate com.wisonic.uniqc.domain.repository.followup.task.FollowupTaskRepository$MockitoMock$542319824.toString()
问题代码行：  
```java
when(mockFollowupTaskRepository.pageExpertTask(any(PageNumber.class), any(PageSize.class),
                eq(departmentId), any(QcGroupId.class), eq(Collections.singletonList("2024-02")),
                any(QcExpertId.class))).thenReturn(followupExpertTaskPageInfo);
```
分析一：参数匹配器使用错误，参数中有用到 any() 匹配器的话，所有参数都应该采用参数匹配器，any() 和 eq()。    
分析二：eq 参数匹配器和 any 参数匹配器冲突，经过验证，不会冲突，以下代码正确：
```java
when(mockFollowupTaskRepository.pageExpertTask(any(PageNumber.class), any(PageSize.class),
                eq(departmentId), any(QcGroupId.class), any(List.class),
                any(QcExpertId.class))).thenReturn(followupExpertTaskPageInfo);
```
确定的原因：List 类型传入参数时不能用 eq 参数匹配器，要么用 `any(List.class)` 匹配，要么用 `argThat` 精确匹配
```java
when(mockFollowupTaskRepository.pageExpertTask(any(PageNumber.class), any(PageSize.class),
    eq(departmentId), any(QcGroupId.class), argThat(list -> list.containsAll(studyMonthList)),
    any(QcExpertId.class))).thenReturn(followupExpertTaskPageInfo);
```



## 在测试时模拟抛出一个异常报错
```
org.mockito.exceptions.base.MockitoException:
Checked exception is invalid for this method!
Invalid: com.wisonic.common.api.constants.exceptions.FeignException: Feign Exception
```

可能原因分析：受检查机制在于，如果代码在运行中需要抛出受检查异常，则对应方法签名后必须声明式的再抛出，即throws IOException，或者同代码块内catch。如java.io包下的大多数方法一样，会在方法上标注throws IOException，这样做的目的就是让调用者知道这个方法可能存在网络连接、文件不存在等导致的IO异常，在代码运行前要做好这方面逻辑的检查！这也是Java受检查异常设计初的目的，它会在代码编译期就开始生效！在模拟时可以通过 doThrow 去模拟抛出异常。   

处理方法：经过排查，业务逻辑代码中没有抛出 FeignException 的地方，因此修改业务逻辑代码并且不需要模拟这一个。**值得注意的是，自定义的异常肯定是需要自己手动 new 一个抛出的！**